services:
  addition-service:
    build:
      context: .
      dockerfile: additionservice/Dockerfile
    image: addition-service
    deploy:
      replicas: 3
  
  subtraction-service:
    build:
      context: .
      dockerfile: subtractionservice/Dockerfile
    image: subtraction-service
    deploy:
      replicas: 3
  
  gateway-service:
    build:
      context: .
      dockerfile: gatewayservice/Dockerfile
    image: gateway-service
    deploy:
      replicas: 3

  database-service:
    build: 
      context: .
      dockerfile: databaseservice/Dockerfile
    image: database-service
    deploy:
      replicas: 3
  
  client-service:
    build:
      context: .
      dockerfile: Client/Dockerfile
    image: client-service
    deploy:
      replicas: 3