services:
  addition-service:
    build:
      context: .
      dockerfile: additionservice/Dockerfile
    image: addition-service
    ports:
    - "3003:3003"
    deploy:
      replicas: 3
  
  subtraction-service:
    build:
      context: .
      dockerfile: subtractionservice/Dockerfile
    image: subtraction-service
    ports:
    - "3002:3002"
    deploy:
      replicas: 3
  
  gateway-service:
    build:
      context: .
      dockerfile: gatewayservice/Dockerfile
    image: gateway-service
    ports:
    - "3001:3001"
    deploy:
      replicas: 3

  database-service:
    build: 
      context: .
      dockerfile: databaseservice/Dockerfile
    image: database-service
    ports:
    - "3004:3004"
    deploy:
      replicas: 3
  
  client-service:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: client-service
    ports:
    - "3000:3000"
    deploy:
      replicas: 3

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"